ALTER TABLE OCHAT_NOTIFICATION_TARGET DROP CONSTRAINT UNQ_OCHAT_NOTIFICATION_TARGET_0
ALTER TABLE OCHAT_MESSAGE DROP CONSTRAINT FK_OCHAT_MESSAGE_SENDER
ALTER TABLE OCHAT_MESSAGE DROP CONSTRAINT FK_OCHAT_MESSAGE_MESSAGE_GROUP_ID
ALTER TABLE OCHAT_USER_GROUP DROP CONSTRAINT FK_OCHAT_USER_GROUP_MESSAGE_GROUP_ID
ALTER TABLE OCHAT_USER_GROUP DROP CONSTRAINT FK_OCHAT_USER_GROUP_MESSAGE_USER_ID
DROP TABLE OCHAT_NOTIFICATION_TARGET
DROP TABLE OCHAT_MESSAGE_USER
DROP TABLE OCHAT_MESSAGE_GROUP
DROP TABLE OCHAT_MESSAGE
DROP TABLE OCHAT_USER_GROUP
DELETE FROM OCHAT_ID_GENERATOR WHERE GENERATOR_NAME = 'NotificationTarget'
DELETE FROM OCHAT_ID_GENERATOR WHERE GENERATOR_NAME = 'Message'
DELETE FROM OCHAT_ID_GENERATOR WHERE GENERATOR_NAME = 'MessageUser'
DELETE FROM OCHAT_ID_GENERATOR WHERE GENERATOR_NAME = 'MessageGroup'
